services:
  mariadb:
    image: docker.io/mariadb:10.6
    platform: linux/amd64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MARIADB_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  # Enable PostgreSQL only if you use it, see development/README.md for more information.
  # postgresql:
  #   image: postgres:11.8
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #   volumes:
  #     - postgresql-data:/var/lib/postgresql/data

  # Enable Mailpit if you need to test outgoing mail services
  # See https://mailpit.axllent.org/
  #  mailpit:
  #    image: axllent/mailpit
  #    volumes:
  #      - mailpit-data:/data
  #    ports:
  #      - 8025:8025
  #      - 1025:1025
  #    environment:
  #      MP_MAX_MESSAGES: 5000
  #      MP_DATA_FILE: /data/mailpit.db
  #      MP_SMTP_AUTH_ACCEPT_ANY: 1
  #      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  redis-cache:
    image: docker.io/redis:alpine
    platform: linux/amd64

  redis-queue:
    image: docker.io/redis:alpine
    platform: linux/amd64

  # adminer:
  #   image: docker.io/library/adminer:latest
  #   platform: linux/amd64
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mariadb
  #   ports:
  #     - "${DB_VIEWER_PORT:-8080}:8080"

  whodb:
    image: clidey/whodb:latest
    ports:
      - "${DB_VIEWER_PORT:-8080}:8080"

  frappe:
    image: docker.io/frappe/bench:latest
    platform: linux/amd64
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ..:/workspace:cached
      # Enable if you require git cloning
      # - ${HOME}/.ssh:/home/frappe/.ssh
    working_dir: /workspace/project_name/source
    ports:
      - "${FRAPPE_PORT_START:-8000}-${FRAPPE_PORT_END:-8005}:8000-8005"
      - "${FRAPPE_ALT_PORT_START:-9000}-${FRAPPE_ALT_PORT_END:-9005}:9000-9005"
volumes:
  mariadb-data:
  #postgresql-data:
  #mailpit-data:

networks:
  project_name:
    driver: bridge